version: '3.9'
services:
  front:
    restart: on-failure
    build: ./nginx
    # depends_on:
    #   - server
    ports:
      - "80:80"
  server:
    restart: on-failure
    build: ./server
    env_file:
      - ./server.env
    depends_on:
      - db
    # ports:
    #   - "80:80"
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: docker
      MYSQL_PASSWORD: password 
      MYSQL_DATABASE: expense_tracker
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: password
    ports:
      - "3307:3307"
  